// GENERATED by scripts/snapshot-viva-stations.mjs — do not edit by hand.
// Regenerate with: npm run snapshot:viva
// Snapshot of VIVA's station roster, used as a fallback when the live
// roster request fails at runtime.
// Not yet generated: run the script from a machine that can reach
// sjofartsverket.se and commit the result.

export interface VivaSnapshotStation {
  id: number;
  name: string;
  lat: number;
  lon: number;
}

export const VIVA_STATIONS_SNAPSHOT: VivaSnapshotStation[] = [];
